# frozen_string_literal: true

source 'https://rubygems.org'

gem 'chunky_png', '~> 1.3', '>= 1.3.5'
gem 'dry-schema'
gem 'forme'
gem 'roda'
gem 'tilt'

group :development do
  gem 'rerun'
  gem 'rubocop'
end
